name: Auto IPTV Pipeline

on:
  schedule:
    - cron: "0 4 * * *"  # 每天凌晨4点（UTC时间）
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp requests

      - name: Run main script
        run: python main.py

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update IPTV channels [skip ci]"
            git push
          fi
