name: Daily Update

on:
  schedule:
    - cron: '55 0 */2 * *'  # 每2天凌晨00点55分执行任务（UTC时间）
  workflow_dispatch:
    branches:
      - main  # 仅在main分支上允许手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0  # 获取完整的提交历史

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
      continue-on-error: true  # 如果安装失败，继续执行

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests difflib

    - name: Run Python script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TZ: Asia/Shanghai  # 设置时区为上海
      run: |
        python main.py

    - name: Upload output files as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-files
        path: output/
        retention-days: 7  # 保留7天

    - name: Commit and push if changed
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Auto-update: $(date +%Y-%m-%d %H:%M:%S)'
        add: 'output/'
        push: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send notification on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🚨 Daily Update Workflow Failed',
            body: 'The daily update workflow failed. Please check the logs: ' + process.env.GITHUB_SERVER_URL + '/' + process.env.GITHUB_REPOSITORY + '/actions/runs/' + process.env.GITHUB_RUN_ID,
            labels: ['bug']
          })
